- .eslintrc.js
- content.js
I added [ESLint](https://eslint.org/) to the project so contributors can lint their changes using a [text editor plugin](https://hackernoon.com/what-is-eslint-how-do-i-set-it-up-on-atom-70f270f57296), [CLI](https://eslint.org/docs/user-guide/command-line-interface), and/or [CI](https://github.com/danielhickman/a2vhsite/blob/master/package.json#L33). I used the existing code and the recommending settings to create the config.
Let me know if you need help setting up Travis CI if you'd like to have it lint pull requests — I think it's a great idea that should be a quick and free addition — or anything else relating to using a linter.
> Add ESLint & correct definitions

- .eslintrc.js
- .travis.yml
1. Perform the first two steps of Travis's [Getting started](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI) (just creating an account and adding the repo) making sure you use the free-for-open-source version `travis-ci.org`.
2. Then merge this PR to add the config. The commit to the chrome branch will trigger its first build upon merging.
Once that's complete all PRs will have a TravisCI check. You could also add the badge to the README.
```md
[![Travis](https://img.shields.io/travis/bijij/ViewImage.svg)](https://travis-ci.org/bijij/ViewImage)
```
[![Travis](https://img.shields.io/travis/bijij/ViewImage.svg)](https://travis-ci.org/bijij/ViewImage)
> TravisCI config for linting

- _locales/no/messages.json
Added translation for Norwegian to `/_locales/no/messages.json`.
> Created Norwegian messages.json translation

- _locales/pt-BR/messages.json
Translated messages.json to Brazilian Portuguese.
> Brazilian Portuguse Translation

- _locales/no/messages.json
- _locales/se/messages.json
Translated `messages.json` to Swedish.
> Swedish translation

- _locales/en/messages.json
- _locales/es/messages.json
Fixes a couple grammatical mistakes in the default English locale and adds a Spanish locale.
> Add Spanish Language locale and fixes some problems with English Language locale

- _locales/cs/messages.json
Translated `messages.json` to Czech.
> Czech translation

- _locales/fr-CA/messages.json
Translated `messages.json` to French Canadian.
> Added French Canadian locales.

- _locales/es/messages.json
> Spanish locales translation fixes

- _locales/tr/messages.json
Added Turkish language locales.
> Added Turkish locales

- _locales/hu/messages.json
Added translation for Hungarian to /_locales/hu/messages.json .
> Hungarian translation

- _locales/pl/messages.json
Added translation for Polish to /_locales/pl/messages.json
> Polish translation

- _locales/sl/messages.json
Add Slovenian translation to _locales/sl/messages.json
> Add Slovenian translation

- _locales/sl/messages.json
Slovenian translation for version 1.7
Fix of previous translation
> Slovenian translation for version 1.7

- _locales/fr/messages.json
Hello,
The translations have been updated for better accuracy and a whitespace removed.
Best Regards,
Codarren
> Corrected French translations

- _locales/hu/messages.json
Hungarian translation is updated
> Hungarian translation [UPDATED]

- _locales/pl/messages.json
Updated messages.json for 1.7.2
> Polish translation for 1.7.2

- js/content-script.js
One bodge coming right up!
This, however, is not sustainable 😢
Google is going to change the classes again and again. There needs to be a deeper redesign of element selection. I would do it, but I don't have much time nowadays. Bodging from time to time is all I can manage (thank's college... 😕) So I'm counting on you @bijij!
Fixes #108 and #107.
> Updated for new class tags

- _locales/it/messages.json
Hello @bijij,
Here a little update for the italian localization.
> Italian translation update

- _locales/ja/messages.json
> Add japanese (ja)

- js/content-script.js
Updated classes used on image search pages
> CSS classes fix in content-script.js

- js/content-script.js
Primarily useful when trying to find larger ones (larger than 20MP for example). Fixes #131
> Add extra method to find images

- _locales/en/messages.json
- html/options.html
- js/background.js
- js/content-script.js
> Add no-referrer option

- _locales/si/messages.json
I have added Sri Lankan Native Language Sinhala to the Localization. I am grateful if you can add this. Thank you for this awesome Extension.
> Local Language Sinhala - Sri Lanka Added

- js/content-script.js
For the new update to the website
> Fix imageText CSS class

- _locales/hu/messages.json
Hungarian translation is updated.
"Hide Share button"
(based on "Hide annoying share button #112")
> Hungarian translation [UPDATED] (based on #112)

- _locales/it/messages.json
Hello @bijij,
here another update for the italian localization.
> Update italian translation with hide-referrer option

- _locales/es/messages.json
This PR is an update to the Spanish translation with the newer strings which hadn't been translated yet.
> Update es translation

- _locales/ca/messages.json
This pull requests adds the Catalan translation.
Love your extension, @bijij!
> Add ca translation
